language: node_js
node_js:
  - '9'
  - '8'
  - '7'
install:
  - npm install
deploy:
  - provider: script
    script: env | sort
  - provider: script
    skip_cleanup: true
    script: sh .travis/pu.sh
    on:
      tags: false
      node: 8
      repo: Azure-Samples/react-aad-msal
  - provider: npm
    email: "liliankasem@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: 8
      repo: Azure-Samples/react-aad-msal
  - provider: releases
    api_key:
      secure: o2qIYtsYuo5r8M/gkU9teD45/cp7uc9SP6sdmSKZlbxeh7gpv8q42QYNebBNaELBXepa2H+oCq3yh4GlhJbQ1glj+n+Ccr6fUosaPE9M0aJ3ECjI6twgX+As2g30Xj0UIiysORD8zGCKAuSecPkydE+/a/GXtA3TxReeDWVmPVrLnkx//sP00+S/hdRK8ocbARFRBU3VKltC6vs+zuBK8ggX8Ab71uBSiuceGdvgWEjy18zTeiJ2a2Ws9geSRgJjA1cW1tFhygIDfuePHkX9q0jvo9e7oxyMFX2iXSBfoyrT/AiuppzyG8IJZA/O1eLnhHWxRzRkQ7kJ4E90c2gRGOmo2CSqeUgv3eRuv183aWfPj0UvgqG/6lRUGF1QCyDU6yn/99T3XE8Uc7DkJGiFsUL/g1nP2FMqRRpkQLRsQFcdNxf8nO/ZzMXBI67Kryzm7clSg7qzQ8mz9xbqtvVAeflvDiGXnC5yMg1W/Ri40X/NsntSSLAn38MTs7qMpYVfnZrIiWm7jFRIkM023l9hLu5kOPWQQxoZTk6wZWbZkw3Q7yExmcTfA2LLJYqzSrQGRj8zO7RcqsSLGwOslr8a25d7mSIoUHZWMef0b1VNq9r5xEWhBJeA1V/zwRMWMuPzSomdG0A7oQEVvipayboeKQ8iPskJrvXG6YNqT2apfwo=
    file_glob: true
    file: dist/*
    on:
      tags: true
      node: 8
      repo: Azure-Samples/react-aad-msal
env:
  global:
    secure: TljZCsFri7z/qySGC6p0JAoiLG/0IfAfwao1KxSKKblgUl6Q7yTGxet+W+6XPorMPRqZNlKtUqPKTZoWtRj7jJykjJXqqMF2SywuJq0+ldYPGWDA47cmpQcZ0tRCnrar+Fd+Ti5eItYbzaK7Wiy3eQWQYm5//9aOzTJe0gqImEV17lxmpcf/YlUSZE7YZbMu9Xxe6JqY7EQ6g3mWB7LXdgIRoMT6bbHneTsmBQDJjbMhH9yGpNY9aMN0mrN7m7uBLtBATzvJWUM3nNbokje5VxwJEr7Q13QeTIBUPOPJkGPlS1rcN3Fl86z4IyXZC+uVfeP0fBZFMpAbcgNceeHv3hnwnmx8ysPO00Js2ln/5jfVLuAqKfPjJ3Vdhvsz5mYgPyvi03v19+IM5SVvWT/Y8do1btdICkF+s0erMh1MWGwP94CI4DSJaM+lbKEJSO6oPZMubzTyZkDgu54plC/Y4gyVNKRetK1mkJ7lMwkHsZz/oLjqWFgc2QKe/H2o5ypaIqQm7zH5qWjtn5nGt3+9D9Xc6+OrK/scWTWpgnoOM33Bh/K4BP/sO3imcx9Lqs98ENSQJdhsBHno6MyBjPbVy4GPShhcYAh7Q4cyeH5lV4k0kDnuDo8Y/0gGxOK5QR1s+7uRHHWA9NCHwrUJiXygIrPFGFEWMUtAmx1kY+BOcDg=
